//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Joolie.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class JOOLIEEntities1 : DbContext
    {
        public JOOLIEEntities1()
            : base("name=JOOLIEEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Credential> Credentials { get; set; }
        public virtual DbSet<Manufacturer> Manufacturers { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Property> Properties { get; set; }
        public virtual DbSet<PropertyValue> PropertyValues { get; set; }
        public virtual DbSet<Search> Searches { get; set; }
        public virtual DbSet<SubCategory> SubCategories { get; set; }
        public virtual DbSet<TechSpecFilter> TechSpecFilters { get; set; }
        public virtual DbSet<TypeFilter> TypeFilters { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<tblCategorySubCategory> tblCategorySubCategories { get; set; }
    
        public virtual int Search_Delete(string subCategory)
        {
            var subCategoryParameter = subCategory != null ?
                new ObjectParameter("SubCategory", subCategory) :
                new ObjectParameter("SubCategory", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Search_Delete", subCategoryParameter);
        }
    
        public virtual int Search_Insert(string subCategory, string category)
        {
            var subCategoryParameter = subCategory != null ?
                new ObjectParameter("SubCategory", subCategory) :
                new ObjectParameter("SubCategory", typeof(string));
    
            var categoryParameter = category != null ?
                new ObjectParameter("Category", category) :
                new ObjectParameter("Category", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Search_Insert", subCategoryParameter, categoryParameter);
        }
    
        public virtual int Search_Update(string subCategory, string category)
        {
            var subCategoryParameter = subCategory != null ?
                new ObjectParameter("SubCategory", subCategory) :
                new ObjectParameter("SubCategory", typeof(string));
    
            var categoryParameter = category != null ?
                new ObjectParameter("Category", category) :
                new ObjectParameter("Category", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Search_Update", subCategoryParameter, categoryParameter);
        }
    
        public virtual ObjectResult<SearchPage_Result> SearchPage()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchPage_Result>("SearchPage");
        }
    
        public virtual ObjectResult<Nullable<int>> spGeSubCategoryID_Products(string subCategory)
        {
            var subCategoryParameter = subCategory != null ?
                new ObjectParameter("subCategory", subCategory) :
                new ObjectParameter("subCategory", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("spGeSubCategoryID_Products", subCategoryParameter);
        }
    
        public virtual ObjectResult<spGetCategoryAndSubcategory_Result> spGetCategoryAndSubcategory(Nullable<int> productID)
        {
            var productIDParameter = productID.HasValue ?
                new ObjectParameter("ProductID", productID) :
                new ObjectParameter("ProductID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetCategoryAndSubcategory_Result>("spGetCategoryAndSubcategory", productIDParameter);
        }
    
        public virtual ObjectResult<spGetComparedProductsDetails_Result> spGetComparedProductsDetails(Nullable<int> productID)
        {
            var productIDParameter = productID.HasValue ?
                new ObjectParameter("ProductID", productID) :
                new ObjectParameter("ProductID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetComparedProductsDetails_Result>("spGetComparedProductsDetails", productIDParameter);
        }
    
        public virtual ObjectResult<spGetManufacturereAndImage_Result> spGetManufacturereAndImage(Nullable<int> productID)
        {
            var productIDParameter = productID.HasValue ?
                new ObjectParameter("ProductID", productID) :
                new ObjectParameter("ProductID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetManufacturereAndImage_Result>("spGetManufacturereAndImage", productIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> spGetPropertyIDByName_Property(string propertyName)
        {
            var propertyNameParameter = propertyName != null ?
                new ObjectParameter("propertyName", propertyName) :
                new ObjectParameter("propertyName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("spGetPropertyIDByName_Property", propertyNameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> spGetPropertyMax_TechSpecFilter(Nullable<int> propertyID)
        {
            var propertyIDParameter = propertyID.HasValue ?
                new ObjectParameter("propertyID", propertyID) :
                new ObjectParameter("propertyID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("spGetPropertyMax_TechSpecFilter", propertyIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> spGetPropertyMin_TechSpecFilter(Nullable<int> propertyID)
        {
            var propertyIDParameter = propertyID.HasValue ?
                new ObjectParameter("propertyID", propertyID) :
                new ObjectParameter("propertyID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("spGetPropertyMin_TechSpecFilter", propertyIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> spGetSubCategoryID_Products(string subCategory)
        {
            var subCategoryParameter = subCategory != null ?
                new ObjectParameter("subCategory", subCategory) :
                new ObjectParameter("subCategory", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("spGetSubCategoryID_Products", subCategoryParameter);
        }
    }
}
